# Generated by Django 3.2.7 on 2021-09-19 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 16, 32, 15, 474773)),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='repository',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
