# Generated by Django 3.2.7 on 2021-09-19 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 17, 36, 20, 790971)),
        ),
    ]
